on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
   
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R packages 
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: 
            any::rmarkdown
            any::unmarked
            any::ggplot2
            any::here
          extra-packages: any::checkmate, any::data.table, any::posterior, any::processx
        
      - name: Cache CmdStan
        uses: actions/cache@v4
        with:
          path: ~/.cmdstan
          key: cmdstan-${{ runner.os }}-v2

      - name: Install cmdstanr
        run: |
          Rscript -e 'install.packages("cmdstanr", repos="https://mc-stan.org/r-packages/")'

      - name: Install CmdStan
        run: |
          Rscript -e 'cmdstanr::install_cmdstan(cores = 2)'
            
      - name: Render qmd files
        run: |
          mkdir build
          quarto render index.qmd --output-dir build
      
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
